// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiay.Models;

#nullable disable

namespace WebBanGiay.Migrations
{
    [DbContext(typeof(DbwebGiayOnlineContext))]
    [Migration("20241024073113_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanGiay.Models.Attribute", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attribute_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("AttributeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("attribute_name");

                    b.HasKey("AttributeId")
                        .HasName("PK__attribut__9090C9BB6D03B184");

                    b.ToTable("attribute", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("brand_name");

                    b.HasKey("BrandId")
                        .HasName("PK__brand__5E5A8E273CA2B74C");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Colour", b =>
                {
                    b.Property<int>("ColourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("colour_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColourId"));

                    b.Property<string>("ColourName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("colour_name");

                    b.HasKey("ColourId")
                        .HasName("PK__colour__38955022F3DFA4F0");

                    b.ToTable("colour", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("coupon_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("coupon_code");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("discount_percentage");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("CouponId")
                        .HasName("PK__coupon__58CF63895EE0BE10");

                    b.HasIndex(new[] { "CouponCode" }, "UQ__coupon__ADE5CBB7EF1D0423")
                        .IsUnique()
                        .HasFilter("[coupon_code] IS NOT NULL");

                    b.ToTable("coupon", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CusAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cus_address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("CustomerId")
                        .HasName("PK__customer__CD65CB85B82E4FE8");

                    b.HasIndex(new[] { "Email" }, "UQ__customer__AB6E61644AEADEE4")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int")
                        .HasColumnName("coupon_id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int")
                        .HasColumnName("shipping_address_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("OrderId")
                        .HasName("PK__order__4659622958D90153");

                    b.HasIndex("CouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("StatusId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("ShoeItemId")
                        .HasColumnType("int")
                        .HasColumnName("shoe_item_id");

                    b.HasKey("OrderItemId")
                        .HasName("PK__order_it__3764B6BC5E06BAA7");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShoeItemId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderNote", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("note_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoteText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note_text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.HasKey("NoteId")
                        .HasName("PK__order_no__CEDD0FA4EFC50179");

                    b.HasIndex("OrderId");

                    b.ToTable("order_notes", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__order_st__3683B531643A7DD2");

                    b.ToTable("order_status", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("method_name");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__payment___8A3EA9EB458D075A");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("RoleId")
                        .HasName("PK__role__760965CCED52F0EC");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.RoleAccount", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("RoleId", "AccountId")
                        .HasName("PK__RoleAcco__F9B314400B671812");

                    b.HasIndex("AccountId");

                    b.ToTable("RoleAccount", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.ShippingAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("street_address");

                    b.HasKey("AddressId")
                        .HasName("PK__shipping__CAA247C82568C55C");

                    b.HasIndex("CustomerId");

                    b.ToTable("shipping_address", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<string>("CareInstructions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("care_instructions");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("ShoeDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shoe_description");

                    b.Property<string>("ShoeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shoe_name");

                    b.HasKey("ShoeId")
                        .HasName("PK__shoe__3AC0314EB0506C92");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("shoe", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeAttribute", b =>
                {
                    b.Property<int>("ShoeId")
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("attribute_value");

                    b.HasKey("ShoeId", "AttributeId")
                        .HasName("PK__shoe_att__93C93DD5E2782B71");

                    b.HasIndex("AttributeId");

                    b.ToTable("shoe_attribute", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("PK__shoe_cat__D54EE9B4FFA3D24E");

                    b.HasIndex("BrandId");

                    b.ToTable("shoe_category", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int?>("ShoeId")
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    b.HasKey("ImageId")
                        .HasName("PK__shoe_ima__DC9AC955AFF94A72");

                    b.HasIndex("ShoeId");

                    b.ToTable("shoe_image", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeItem", b =>
                {
                    b.Property<int>("ShoeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shoe_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoeItemId"));

                    b.Property<int?>("ColourId")
                        .HasColumnType("int")
                        .HasColumnName("colour_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("sale_price");

                    b.Property<int?>("ShoeId")
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int")
                        .HasColumnName("size_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sku");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.HasKey("ShoeItemId")
                        .HasName("PK__shoe_ite__9ECD427BA415457D");

                    b.HasIndex("ColourId");

                    b.HasIndex("ShoeId");

                    b.HasIndex("SizeId");

                    b.ToTable("shoe_item", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("size_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("SizeName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size_name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("SizeId")
                        .HasName("PK__size__0DCACE31C597D616");

                    b.ToTable("size", (string)null);
                });

            modelBuilder.Entity("WebBanGiay.Models.Order", b =>
                {
                    b.HasOne("WebBanGiay.Models.Coupon", "Coupon")
                        .WithMany("Orders")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK__order__coupon_id__693CA210");

                    b.HasOne("WebBanGiay.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__order__customer___656C112C");

                    b.HasOne("WebBanGiay.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("FK__order__payment_m__66603565");

                    b.HasOne("WebBanGiay.Models.ShippingAddress", "ShippingAddress")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingAddressId")
                        .HasConstraintName("FK__order__shipping___68487DD7");

                    b.HasOne("WebBanGiay.Models.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__order__status_id__6754599E");

                    b.Navigation("Coupon");

                    b.Navigation("Customer");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ShippingAddress");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderItem", b =>
                {
                    b.HasOne("WebBanGiay.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__order_ite__order__6C190EBB");

                    b.HasOne("WebBanGiay.Models.ShoeItem", "ShoeItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("ShoeItemId")
                        .HasConstraintName("FK__order_ite__shoe___6D0D32F4");

                    b.Navigation("Order");

                    b.Navigation("ShoeItem");
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderNote", b =>
                {
                    b.HasOne("WebBanGiay.Models.Order", "Order")
                        .WithMany("OrderNotes")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__order_not__order__70DDC3D8");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebBanGiay.Models.RoleAccount", b =>
                {
                    b.HasOne("WebBanGiay.Models.Customer", "Account")
                        .WithMany("RoleAccounts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__RoleAccou__Accou__5812160E");

                    b.HasOne("WebBanGiay.Models.Role", "Role")
                        .WithMany("RoleAccounts")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RoleAccou__RoleI__571DF1D5");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShippingAddress", b =>
                {
                    b.HasOne("WebBanGiay.Models.Customer", "Customer")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__shipping___custo__5EBF139D");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebBanGiay.Models.Shoe", b =>
                {
                    b.HasOne("WebBanGiay.Models.Brand", "Brand")
                        .WithMany("Shoes")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK__shoe__brand_id__3D5E1FD2");

                    b.HasOne("WebBanGiay.Models.ShoeCategory", "Category")
                        .WithMany("Shoes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__shoe__category_i__3C69FB99");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeAttribute", b =>
                {
                    b.HasOne("WebBanGiay.Models.Attribute", "Attribute")
                        .WithMany("ShoeAttributes")
                        .HasForeignKey("AttributeId")
                        .IsRequired()
                        .HasConstraintName("FK__shoe_attr__attri__4E88ABD4");

                    b.HasOne("WebBanGiay.Models.Shoe", "Shoe")
                        .WithMany("ShoeAttributes")
                        .HasForeignKey("ShoeId")
                        .IsRequired()
                        .HasConstraintName("FK__shoe_attr__shoe___4D94879B");

                    b.Navigation("Attribute");

                    b.Navigation("Shoe");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeCategory", b =>
                {
                    b.HasOne("WebBanGiay.Models.Brand", "Brand")
                        .WithMany("ShoeCategories")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK__shoe_cate__brand__398D8EEE");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeImage", b =>
                {
                    b.HasOne("WebBanGiay.Models.Shoe", "Shoe")
                        .WithMany("ShoeImages")
                        .HasForeignKey("ShoeId")
                        .HasConstraintName("FK__shoe_imag__shoe___48CFD27E");

                    b.Navigation("Shoe");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeItem", b =>
                {
                    b.HasOne("WebBanGiay.Models.Colour", "Colour")
                        .WithMany("ShoeItems")
                        .HasForeignKey("ColourId")
                        .HasConstraintName("FK__shoe_item__colou__44FF419A");

                    b.HasOne("WebBanGiay.Models.Shoe", "Shoe")
                        .WithMany("ShoeItems")
                        .HasForeignKey("ShoeId")
                        .HasConstraintName("FK__shoe_item__shoe___440B1D61");

                    b.HasOne("WebBanGiay.Models.Size", "Size")
                        .WithMany("ShoeItems")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK__shoe_item__size___45F365D3");

                    b.Navigation("Colour");

                    b.Navigation("Shoe");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WebBanGiay.Models.Attribute", b =>
                {
                    b.Navigation("ShoeAttributes");
                });

            modelBuilder.Entity("WebBanGiay.Models.Brand", b =>
                {
                    b.Navigation("ShoeCategories");

                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("WebBanGiay.Models.Colour", b =>
                {
                    b.Navigation("ShoeItems");
                });

            modelBuilder.Entity("WebBanGiay.Models.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanGiay.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RoleAccounts");

                    b.Navigation("ShippingAddresses");
                });

            modelBuilder.Entity("WebBanGiay.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderNotes");
                });

            modelBuilder.Entity("WebBanGiay.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanGiay.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanGiay.Models.Role", b =>
                {
                    b.Navigation("RoleAccounts");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShippingAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebBanGiay.Models.Shoe", b =>
                {
                    b.Navigation("ShoeAttributes");

                    b.Navigation("ShoeImages");

                    b.Navigation("ShoeItems");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeCategory", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("WebBanGiay.Models.ShoeItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebBanGiay.Models.Size", b =>
                {
                    b.Navigation("ShoeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
